[package]
name = "thought"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.32"
sailfish = "0.9"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
eframe = { version = "0.32", default-features = false, features = [
    "glow",
    "wayland",
    "default_fonts",
] }
pulldown-cmark = { version = "0.13", default-features = false, features = [
    "html",
] }

[profile.release]
lto = true
strip = true
